### ISSUE TITLE
react-native 0.60

### ISSUE THREAD

**Issue by burtek** [vonovak/react-native-add-calendar-event#70] opened 2019-07-10 12:58 UTC
Is this package compatible with react-native 0.60, incl. new auto-linking feature?

**Comment by vonovak** [comment] 2019-07-10 15:22
hi, I don't know because I have not tried it. Feel free to try it and let me know, thanks.

**Comment by PierreCapo** [comment] 2019-07-16 20:54
I've just tested on react-native 0.60.3 and this lib is not auto-linked, you need to do the `react-native link react-native-add-calendar-event` command

**Comment by reddeguzman** [comment] 2019-10-09 19:44
> I've just tested on react-native 0.60.3 and this lib is not auto-linked, you need to do the `react-native link react-native-add-calendar-event` command

did it work?

**Comment by ldco2016** [comment] 2019-10-30 15:20
@vonovak, I was looking at this as an alternative to `react-native-calendar-events` but it looks like it has not been updated for autolinking for React Native 60+. Our `react-native-calendar-events` was working in the legacy 0.53.3 version, but since the upgrade to 0.60.4, it stopped working. Even when upgrading to version 1.7.3 from 1.6.1 and unfortunately I have had no communication from its author on what the problem could be. Autolinking? Incompatibility with something else?

If anyone has information on how `react-native-calendar-events` is working or not working with React Native 60+, please let me know. I have tried everything I can think of. You can view it here:
https://stackoverflow.com/questions/58518748/rncalendarevents-saveevent-issues-error-no-calendar-has-been-set

**Comment by vonovak** [comment] 2019-11-01 13:27
I'm closing this since v3 was tested with latest RN. @ldco2016 if you have a problem (as I see in stackoverlow) it'd be nice to add a runnable repro, otherwise its much harder to help.

**Closed by vonovak** 2019-11-01 13:27 UTC

**Comment by ldco2016** [comment] 2019-11-01 15:35
@vonovak , you can use this reproducible demo here:
https://github.com/ldco2016/AwesomeApp
and thank you for offering help.
