### ISSUE TITLE
iOS and Android handle timezone differently

### ISSUE THREAD

**Issue by danielmhanover** [vonovak/react-native-add-calendar-event#51] opened 2018-11-18 19:38 UTC
The following code yields the same (correct) event time on both iOS and Android:

    const date = Platform.select({
      ios: moment(appointment.date),
      android: moment(appointment.date).utc()
    })
    const eventConfig = {
      title: `...`,
      startDate: date.format('YYYY-MM-DDTHH:mm:ss.SSS[Z]'),
      endDate: date.add(1, 'hour').format('YYYY-MM-DDTHH:mm:ss.SSS[Z]'),
    };

**Comment by vonovak** [comment] 2018-11-19 20:30
hi, thanks for reporting. The module expects the dates to be in UTC. If the dates show up differently, it's likely because the devices/emualtors have different time zones setup. I'll close this now, but please let me know if the problem persists, and please add steps to reproduce it. Thanks.

**Closed by vonovak** 2018-11-19 20:30 UTC
