### ISSUE TITLE
App crashes using AddCalendarEvent.presentEventDialog(eventConfig)

### ISSUE THREAD

**Issue by realtebo** [vonovak/react-native-add-calendar-event#43] opened 2018-06-01 13:55 UTC
In my app, every time I try to call 

```javascript
AddCalendarEvent.presentEventDialog(eventConfig);
```

I got an app crash.

I tryed to wrap this call into a try/catch but probably the crash is at Java level and not at JS level.

```javascript
    console.log ('trying to opening calendar');

    try {
      AddCalendarEvent.presentEventDialog(eventConfig)
        .then((eventInfo: { calendarItemIdentifier: string, eventIdentifier: string }) => {

          if (eventInfo) {
            console.warn(JSON.stringify(eventInfo));
          } else {
             console.warn('dismissed');
          }
        })
        .catch((error) => {
           handle error such as when user rejected permissions
           console.warn(error);
        }); 
    } catch (error) {
      console.log('here 4', error);
    }
```

How can I debug this issue?

**Comment by vonovak** [comment] 2018-06-01 13:57
do you at least get some stacktrace? you can launch the app from android studio with debugger attached too, if you wanna do some debugging.

**Comment by realtebo** [comment] 2018-06-04 12:20
I'll try and update this reply. Thanks for this idea.

**Comment by realtebo** [comment] 2018-06-04 13:03
I'm not able to make app runing using android studio, ma using logcat I intercepted this:

```
java.lang.SecurityException: Permission Denial: reading com.android.providers.calendar.CalendarProvider2 uri content://com.android.calendar/events from pid=5439, uid=10100 requires android.permission.READ_CALENDAR, or grantUriPermission()

```
Do we add some permissions to androidmanifest.xml? 

I tried to add 

    <uses-permission android:name="android.permission.READ_CALENDAR" />
    <uses-permission android:name="android.permission.WRITE_CALENDAR" />

but without success

**Comment by udaisshekhawat** [comment] 2018-06-05 08:28
I am facing same issue:

Stack trace:

`06-05 09:26:19.423 25697-25710/com.android.providers.calendar E/DatabaseUtils: Writing exception to parcel
                                                                               java.lang.SecurityException: Permission Denial: reading com.android.providers.calendar.CalendarProvider2 uri content://com.android.calendar/events from pid=24719, uid=10088 requires android.permission.READ_CALENDAR, or grantUriPermission()
                                                                                   at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:631)
                                                                                   at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:501)
                                                                                   at android.content.ContentProvider$Transport.query(ContentProvider.java:213)
                                                                                   at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
                                                                                   at android.os.Binder.execTransact(Binder.java:697)`

`java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                     at android.os.AsyncTask$3.done(AsyncTask.java:353)
                                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                     at java.lang.Thread.run(Thread.java:764)
                                                                  Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.calendar.CalendarProvider2 uri content://com.android.calendar/events from pid=24719, uid=10088 requires android.permission.READ_CALENDAR, or grantUriPermission()
                                                                     at android.os.Parcel.readException(Parcel.java:2004)
                                                                     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                                     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                     at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
                                                                     at android.content.ContentResolver.query(ContentResolver.java:754)
                                                                     at android.content.ContentResolver.query(ContentResolver.java:704)
                                                                     at android.content.CursorLoader.loadInBackground(CursorLoader.java:64)
                                                                     at android.content.CursorLoader.loadInBackground(CursorLoader.java:54)
                                                                     at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:315)
                                                                     at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
                                                                     at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:64)
                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:266)`

**Comment by vonovak** [comment] 2018-06-05 09:07
The permissions are probably handled slightly differently across os versions and vendors.

Since, unlike you, I don't have a reproduction at hand I suggest you try to ask the READ_CALENDAR permission is index.js along with the WRITE_CALENDAR permission that's already there. Do you think you can try that and ship over a PR / tell me if that works? Thanks.

**Comment by jsispal** [comment] 2018-06-05 09:44
@vonovak I've added a check for `READ_CALENDAR` and that seems to fix the crash on API 26+. Wasn't able to push my branch due to write access on the repo.

**Comment by vonovak** [comment] 2018-06-05 18:34
this is fixed in 1.1.4 or in 2.0.0-rc2

**Closed by vonovak** 2018-06-05 18:34 UTC

**Comment by kannan-rjp** [comment] 2024-04-02 10:16
When you find this, please free to suggest. I have issue with that when call the presentEventDialog, the calendar is opened. App is closed the debug also closed. I couldn't find the reason.
READ_CALENDAR
WRITE_CALENDAR added already in my app

**Comment by tribhuvan-wavemaker** [comment] 2024-11-22 05:54
@kannan-rjp  We also have the same issue. In iOS calendar is opened with event data but after saving the event from the calendar dialog, the is closing/crashing. Let me know if you have found a solution for this.

**Comment by marchiartur** [comment] 2025-01-10 23:58
> @kannan-rjp We also have the same issue. In iOS calendar is opened with event data but after saving the event from the calendar dialog, the is closing/crashing. Let me know if you have found a solution for this.



> When you find this, please free to suggest. I have issue with that when call the presentEventDialog, the calendar is opened. App is closed the debug also closed. I couldn't find the reason. READ_CALENDAR WRITE_CALENDAR added already in my app


```
const granted = await PermissionsAndroid.requestMultiple([
        PermissionsAndroid.PERMISSIONS.READ_CALENDAR,
        PermissionsAndroid.PERMISSIONS.WRITE_CALENDAR,
]);

```
Have you ever tried to use both request permissions?
