### ISSUE TITLE
Build failed: com.android.ide.common.process.ProcessException: Failed to execute aapt

### ISSUE THREAD

**Issue by bencmack** [vonovak/react-native-add-calendar-event#46] opened 2018-08-02 01:06 UTC
Hi, I'm encountering this error when trying to rebuild my project in Android but only after installing this library. I uninstalled the library, everything works, then reinstall and again get this error. I followed all of the instructions in the ReadMe but continue getting this error:

`:react-native-add-calendar-event:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-add-calendar-event:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt`

 Any help would be greatly appreciated. I've scoured the web for solutions and found no hints or solutions.

**Comment by vonovak** [comment] 2018-08-02 05:33
it's possible that this is due to old build tools together with RN 0.56
doing something like [this](https://github.com/react-native-community/react-native-google-signin/pull/462/files) may fix it

**Comment by vonovak** [comment] 2018-11-19 20:33
closing since the issue is outdated; please add a repro if the issue persists

**Closed by vonovak** 2018-11-19 20:33 UTC
Labels: help wanted
